---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ java_local_archive_dir }}'
      delegate_to: localhost
      when: java_use_local_archive

    - name: download JDK for offline install
      get_url:
        url: 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u302-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz'
        dest: '{{ java_local_archive_dir }}/OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz'
        force: no
        use_proxy: yes
        validate_certs: yes
        timeout: '{{ java_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost
      when: java_use_local_archive

  roles:
    - role: ansible-role-java
      java_major_version: '8'
      java_version: '8.0.302+8'
      java_release_name: 'jdk8u302-b08.1'
      java_use_local_archive: yes
      java_redis_filename: 'OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz'
      java_redis_sha256sum: 'cc13f274becf9dd5517b6be583632819dfd4dd81e524b5c1b4f406bdaf0e063a'

  post_tasks:
    - name: verify java facts
      assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
