# code: language=ansible
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_pkg_mgr == 'apt'

    - name: Create local archive directory
      ansible.builtin.file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ java_local_archive_dir }}'
      delegate_to: localhost

    - name: Download JDK for offline install
      ansible.builtin.get_url:
        url: "https://api.adoptium.net/v3/binary/version/{{ 'jdk-17.0.7+7' | urlencode }}/linux/x64/jdk/hotspot/normal/adoptium?project=jdk"  # noqa 204
        dest: '{{ java_local_archive_dir }}/OpenJDK17-jdk_x64_linux_hotspot_17.0.7_7.tar.gz'
        force: false
        timeout: '{{ java_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-java
      java_use_local_archive: true
      java_major_version: '17'
      java_version: '17.0.7+7'
      java_release_name: 'jdk-17.0.7+7'

      java_redis_filename: 'OpenJDK17-jdk_x64_linux_hotspot_17.0.7_7.tar.gz'
      java_redis_sha256sum: 'e9458b38e97358850902c2936a1bb5f35f6cffc59da9fcd28c63eab8dbbfbc3b'

  post_tasks:
    - name: Verify java facts
      ansible.builtin.assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: Install find - required for tests (dnf)
      ansible.builtin.dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
