---
- name: Check for JDK on local box
  ansible.builtin.stat:
    path: '{{ java_local_archive_dir }}/{{ java_redis_filename }}'
  delegate_to: localhost
  register: java_local_file
  ignore_errors: true
  become: false
  when: java_use_local_archive

- name: Copy JDK from local box
  become: true
  ansible.builtin.copy:
    src: '{{ java_local_archive_dir }}/{{ java_redis_filename }}'
    dest: '{{ java_download_dir }}/{{ java_redis_filename }}'
    mode: 'u=rw,go=r'
  when: java_use_local_archive and java_local_file.stat.exists
