---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-java-opensuse
    image: opensuse/leap:15.4

provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-online/converge.yml

verifier:
  name: testinfra
  directory: ../java-min/tests
