# code: language=ansible
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_pkg_mgr == 'apt'

    - name: Create local archive directory
      ansible.builtin.file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ java_local_archive_dir }}'
      delegate_to: localhost

    - name: Download JDK for offline install
      ansible.builtin.get_url:
        url: "https://api.adoptium.net/v3/binary/version/{{ 'jdk-11.0.20+8' | urlencode }}/linux/x64/jdk/hotspot/normal/adoptium?project=jdk"  # noqa 204
        dest: '{{ java_local_archive_dir }}/OpenJDK11U-jdk_x64_linux_hotspot_11.0.20_8.tar.gz'
        force: false
        timeout: '{{ java_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-java
      java_use_local_archive: true
      java_major_version: '11'
      java_version: '11.0.20+8'
      java_release_name: 'jdk-11.0.20+8'
      java_redis_filename: 'OpenJDK11U-jdk_x64_linux_hotspot_11.0.20_8.tar.gz'
      java_redis_sha256sum: '7a99258af2e3ee9047e90f1c0c1775fd6285085759501295358d934d662e01f9'

  post_tasks:
    - name: Verify java facts
      ansible.builtin.assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: Install find - required for tests (dnf)
      ansible.builtin.dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
