---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-java-ubuntu-min-java-max-non-lts
    image: ubuntu:16.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../java-max-non-lts-online/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: ubuntu-min-java-max-non-lts-online

verifier:
  name: testinfra
  directory: ../java-max-non-lts/tests
  lint:
    name: flake8
