---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-java-ubuntu-min-java-max-lts
    image: ubuntu:18.04

provisioner:
  name: ansible
  playbooks:
    converge: ../java-max-lts-online/converge.yml

verifier:
  name: testinfra
  directory: ../java-max-lts/tests
