---
provisioner:
  name: ansible
  inventory:
    group_vars:
      online:
        java_use_local_archive: no
      offline:
        java_use_local_archive: yes
  options:
    extra-vars:
      java_license_declaration: 'I accept the "Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX" under the terms at http://www.oracle.com/technetwork/java/javase/terms/license/index.html'
  lint:
    name: ansible-lint

dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-java-ubuntu-xenial-java10
    image: ubuntu:16.04
    groups:
      - offline

scenario:
  name: java10

verifier:
  name: testinfra
  lint:
    name: flake8
