---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-java-centos-max-java-max-lts
    image: centos:7
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../java-max-lts-offline/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: centos-max-java-max-lts-offline

verifier:
  name: testinfra
  directory: ../java-max-lts/tests
  lint:
    name: flake8
