---
provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-online/converge.yml

dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-java-default
    image: ubuntu:22.04

verifier:
  name: testinfra
  directory: ../java-min/tests
