---
ansible:
  playbook: tests/test.yml
  group_vars:
    online:
      java_use_local_archive: no
    offline:
      java_use_local_archive: yes
  extra_vars:
    java_license_declaration: 'I accept the "Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX" under the terms at http://www.oracle.com/technetwork/java/javase/terms/license/index.html'

dependency:
  name: galaxy

driver:
  name: docker

docker:
  containers:
    - name: ansible-role-java-debian-wheezy
      image: debian
      image_version: '7'
      ansible_groups:
        - online
    - name: ansible-role-java-debian-jessie
      image: debian
      image_version: '8'
      ansible_groups:
        - offline
    - name: ansible-role-java-ubuntu-trusty
      image: ubuntu
      image_version: '14.04'
      ansible_groups:
        - online
    - name: ansible-role-java-ubuntu-xenial
      image: ubuntu
      image_version: '16.04'
      ansible_groups:
        - offline
    - name: ansible-role-java-centos-6
      image: centos
      image_version: '6'
      ansible_groups:
        - online
    - name: ansible-role-java-centos-7
      image: centos
      image_version: '7'
      ansible_groups:
        - offline
    - name: ansible-role-java-fedora-25
      image: fedora
      image_version: '25'
      command: /bin/bash
      ansible_groups:
        - online
    - name: ansible-role-java-opensuse-leap
      image: opensuse
      image_version: '42.2'
      command: /bin/bash
      ansible_groups:
        - online

verifier:
  name: testinfra
