---
provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-online/converge.yml

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-java-default
    image: ubuntu:20.04

verifier:
  name: testinfra
  directory: ../java-min/tests
