---
- name: Converge
  hosts: all

  pre_tasks:
    - name: install Ansible dnf dependency (dnf)
      become: yes
      command: dnf install -y python2-dnf
      args:
        warn: no
      changed_when: no
      when: ansible_pkg_mgr == 'dnf'

    - name: install Ansible zypper dependency (zypper)
      become: yes
      command: zypper install -y python-xml
      args:
        warn: no
      changed_when: no
      when: ansible_pkg_mgr == 'zypper'

    - name: create local archive directory
      local_action: file state=directory mode='u=rwx,go=rx' dest='{{ java_local_archive_dir }}'
      when: java_use_local_archive

    - name: download JDK for offline install
      local_action: >
        get_url
        url='http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz'
        headers='Cookie:oraclelicense=accept-securebackup-cookie'
        dest='{{ java_local_archive_dir }}/jdk-8u131-linux-x64.tar.gz'
        force=no
        use_proxy=yes
        validate_certs=yes
        timeout='{{ java_jdk_download_timeout_seconds }}'
        mode='u=rw,go=r'
      when: java_use_local_archive

    - name: download JCE for offline install
      local_action: >
        get_url
        url='http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip'
        headers='Cookie:oraclelicense=accept-securebackup-cookie'
        dest='{{ java_local_archive_dir }}/jce_policy-8.zip'
        force=no
        use_proxy=yes
        validate_certs=yes
        timeout='{{ java_jdk_download_timeout_seconds }}'
        mode='u=rw,go=r'
      when: java_use_local_archive

  roles:
    - role: ansible-role-java

  post_tasks:
    - name: verify java facts
      assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
