---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-java-ubuntu-max
    image: ubuntu:20.04

provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-offline/converge.yml

verifier:
  name: testinfra
  directory: ../java-min/tests
