---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-java-ubuntu-max
    image: ubuntu:18.04

provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-offline/playbook.yml
  options:
    extra-vars:
      java_license_declaration: 'I accept the "Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX" under the terms at http://www.oracle.com/technetwork/java/javase/terms/license/index.html'
  lint:
    name: ansible-lint

scenario:
  name: ubuntu-max-java-min-offline

verifier:
  name: testinfra
  directory: ../java-min/tests
  lint:
    name: flake8
