---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-java-ubuntu-max
    image: ubuntu:22.04

provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-offline/converge.yml

verifier:
  name: testinfra
  directory: ../java-min/tests
