---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-java-debian-min
    image: debian:9

provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-online/converge.yml

verifier:
  name: testinfra
  directory: ../java-min/tests
