---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-java-debian-min
    image: debian:10

provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-online/converge.yml

verifier:
  name: testinfra
  directory: ../java-min/tests
