---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-java-fedora
    image: fedora:35

provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-online/converge.yml

verifier:
  name: testinfra
  directory: ../java-min/tests
