---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-java-ubuntu-max-arm64
    image: arm64v8/ubuntu:22.04

provisioner:
  name: ansible
  playbooks:
    converge: ../java-max-lts-online/converge.yml

verifier:
  name: testinfra
  directory: ../java-max-lts/tests
