---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-java-centos-max
    image: rockylinux/rockylinux:8

provisioner:
  name: ansible
  playbooks:
    converge: ../java-min-offline/converge.yml

verifier:
  name: testinfra
  directory: ../java-min/tests
