---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-java-ubuntu-min-java-old-lts
    image: ubuntu:18.04

provisioner:
  name: ansible
  playbooks:
    converge: ../java-old-lts-online/converge.yml

verifier:
  name: testinfra
  directory: ../java-old-lts/tests
