---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-java-ubuntu-max-java-max-non-lts
    image: ubuntu:18.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../java-max-non-lts-offline/converge.yml

verifier:
  name: testinfra
  directory: ../java-max-non-lts/tests
