---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ java_local_archive_dir }}'
      delegate_to: localhost

    - name: download JDK for offline install
      get_url:
        url: "https://api.adoptium.net/v3/binary/version/{{ 'jdk-17.0.3+7' | urlencode }}/linux/x64/jdk/hotspot/normal/adoptium?project=jdk"  # noqa 204
        dest: '{{ java_local_archive_dir }}/OpenJDK17-jdk_x64_linux_hotspot_17.0.3_7.tar.gz'
        force: no
        timeout: '{{ java_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-java
      java_use_local_archive: yes
      java_major_version: '17'
      java_version: '17.0.3+7'
      java_release_name: 'jdk-17.0.3+7'
      java_redis_filename: 'OpenJDK17-jdk_x64_linux_hotspot_17.0.3_7.tar.gz'
      java_redis_sha256sum: '81f5bed21077f9fbb04909b50391620c78b9a3c376593c0992934719c0de6b73'

  post_tasks:
    - name: verify java facts
      assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
