---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ java_local_archive_dir }}'
      delegate_to: localhost

    - name: download JDK for offline install
      get_url:
        url: "https://api.adoptopenjdk.net/v3/binary/version/{{ 'jdk-17.0.2+8' | urlencode }}/linux/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk"  # noqa 204
        dest: '{{ java_local_archive_dir }}/OpenJDK17-jdk_x64_linux_hotspot_17.0.2_8.tar.gz'
        force: no
        timeout: '{{ java_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-java
      java_use_local_archive: yes
      java_major_version: '17'
      java_version: '17.0.2+8'
      java_release_name: 'jdk-17.0.2+8'
      java_redis_filename: 'OpenJDK17-jdk_x64_linux_hotspot_17.0.2_8.tar.gz'
      java_redis_sha256sum: '288f34e3ba8a4838605636485d0365ce23e57d5f2f68997ac4c2e4c01967cd48'

  post_tasks:
    - name: verify java facts
      assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
