---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ java_local_archive_dir }}'
      delegate_to: localhost

    - name: download JDK for offline install
      get_url:
        url: "https://api.adoptium.net/v3/binary/version/{{ 'jdk-19.0.2+7' | urlencode }}/linux/x64/jdk/hotspot/normal/adoptium?project=jdk"  # noqa 204
        dest: '{{ java_local_archive_dir }}/OpenJDK19-jdk_x64_linux_hotspot_19.0.2_7.tar.gz'
        force: no
        timeout: '{{ java_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-java
      java_use_local_archive: yes
      java_major_version: '19'
      java_version: '19.0.2+7'
      java_release_name: 'jdk-19.0.2+7'
      java_redis_filename: 'OpenJDK19-jdk_x64_linux_hotspot_19.0.2_7.tar.gz'
      java_redis_sha256sum: '3a3ba7a3f8c3a5999e2c91ea1dca843435a0d1c43737bd2f6822b2f02fc52165'

  post_tasks:
    - name: verify java facts
      assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
