---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-java-debian-min-java-max-lts
    image: debian:11
    platform: linux/arm64/v8

provisioner:
  name: ansible
  playbooks:
    converge: ../java-max-lts-online/converge.yml

verifier:
  name: testinfra
  directory: ../java-max-lts/tests
