---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-java-centos-max-java-max-lts
    image: centos:8
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../java-max-lts-offline/converge.yml

verifier:
  name: testinfra
  directory: ../java-max-lts/tests
